version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - 9000:9000

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    ports:
      - 80:80
    depends_on:
      - app
