services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - 8000:9000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:exampleappkey
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=9000

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: SabangTrip
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
